FloatTech/ZeroBot-Plugin

manager/manager.go, manager/timer.go
1. 按周提醒判断错误
2. 汉字转换周天错误
1. 检查定时参数是否合法
=> 群管定时提醒bug修复

plugin_diana/fansDaily.go
=> 把缺失的函数和结构体声明加上

main.go, plugin_minecraft/info.go, plugin_minecraft/manager.go
=> 新增mc服务器相关功能~

.gitignore, go.mod, main.go, plugin_fortune/fortune.go, plugin_omikuji/sensou.go
=> ✨ 增加运势图片插件

plugin_qingyunke/qingyunke.go
=> fix:给msg进行url编码，解决青云客接口返回错误

plugin_bilibili/fansDaily.go, plugin_vtb_quotation/cron.go
=> 小小的修改一下cron表达式

README.md
按照main.go里面import的顺序把插件排了一遍，顺便改成了折叠版
=> [水pr]整理README.md

README.md
=> 🐛README.md查缺补漏

plugin/bilibili_parse/bilibili_parse.go
修复 粉丝数据获取出错
优化 可能会出现匹配到合并转发中的id的问题
优化 简化数据显示
优化 不返回无效链接的错误
=> fix:bilibiliparse粉丝数据获取出错

README.md, plugin/bilibili/bilibili.go, plugin/coser/coser.go, plugin/lolicon/lolicon.go, plugin/score/sign_in.go, plugin/ymgal/model.go, plugin/ymgal/ymgal.go
=> Refactor image

plugin/tarot/tarot.go
=> fix: []message.MessageSegment->message.Message

plugin/qqwife/command.go, plugin/qqwife/function.go
删除db文件之后第一个娶群友只创建了表格直接return了，没有给updatetime写入更新时间，导致花名册读取不到时间又重新重置了一遍
=> fix #433 修复重置之后第一个人娶群友不登记问题

plugin/music/selecter.go
=> fix:换成网易云官方的api

plugin/music/selecter.go
1. 酷我音乐音乐直链url和参数修改，添加音乐卡片自定义参数。
2. 酷狗音乐添加音乐卡片自定义参数。
=> ⚡️ update music

plugin/warframeapi/main.go, plugin/warframeapi/world.go
1.转发多条消息，改为了合并
2.增加了25条物品查询上限
3.修复了gameWorld的锁未初始化的问题
4.修改了超时时间为30秒
=> fix 初始化错误，改善阅读体验

plugin/ai_reply/main.go
=> fix: ent->enr

plugin/coser/coser.go
Coser 插件这段代码如果当 arr 的长度为 0 的时候，取长度为0随机数就会 panic。
=> [Coser plugin] Fix:  Intn Panic when the len is 0

plugin/ai_false/ai_false.go
=> fix slow aifalse

plugin/baidu/search.go
=> fixed: 修复一个正则匹配的小问题

plugin/steam/steam.go
=> fix:更改steam api的申请地址

go.mod, go.sum, plugin/score/draw.go, plugin/score/sign_in.go
=> add: score new style

go.mod, go.sum, plugin/gif/context.go, plugin/gif/gif.go
解决BOT和gocq不在同一个服务器的时候，生成的gif文件发送问题
=> ♿️ gif改为使用base64发送

plugin/mcfish/main.go, plugin/mcfish/store.go
Fix mcfish Plugin
1.修复重复指令刷钱问题
2.修复卖唱片逻辑
3.新增规则
=> Fix mcfish Plugin

plugin/baidu/search.go
=> baidu: 修复要查询的内容有空格时会导致无响应的问题

plugin/mcfish/pole.go
=> (fix #914) mcfish bug：out of range

plugin/gif/run.go, plugin/qqwife/function.go
适配at的cq码中包含name导致的gif和qqwife无法响应at的问题
=> 修改gif和qqwife的at解析问题

plugin/qqwife/favorSystem.go, plugin/robbery/robbery.go
=> fix(qqwife&robbery): at 解析问题

plugin/mcfish/main.go
1. 修复商品数量大于250时，商品价格浮动区间数值异常
2. 修复出售限制未生效的问题。（时间未更新）
=> fix: two bugs in mcifsh

plugin/aifalse/main.go, plugin/score/sign_in.go
=> chore:替换图片API地址,感谢大自然的馈赠

plugin/mcfish/main.go
=> fix:[mcfish]User purchases fish pole initialization

plugin/niuniu/main.go
本来是想jj完后返回一个niuID来进行操作的，还有自定义回复，但是我看到好像有个pr已经把赎牛牛的bug修了，那就先不管了
=> fix:修复注销牛牛无法进行累加收费的问题&&优化代码

plugin/bilibili/bilibili_parse.go
=> B站视频解析 视频上传开关
