plugin_image_finder/keyword.go

1.代理域名从.cat替换成.re;
2.Large尺寸图无法在PC QQ看见，已更改成Medium尺寸

修复代理域名，解决PC端无法看图问题

---

plugin_b14/main.go
plugin_bilibili_push/bilibili_push.go
plugin_cangtoushi/cangtoushi.go
plugin_fortune/fortune.go

- fortune的设置底图功能
- b14的加密功能
***
本想继续调整藏头诗和b14的解密，但是涉及到正则触发了ORZ

优化在两个命令中使用空格分隔的体验

---

plugin/manager/manager.go

从url正则中去除用字,以防止url中包含用字前缀导致图片显示失败

从url正则中去除用字

---

plugin/manager/manager.go

Add {gid} {groupname} ; replace {id} with {uid} ; Write UnescapeCQCodeText  into database instead

新增 {gid} {groupname}

---

plugin/baiduaudit/audit.go

fix baiduaudit的正则错误

---

plugin/drawlots/main.go

update: drawlots

---

README.md
main.go
plugin/dish/dish.go

这个PR新增了一个插件：
程序员做饭指南(Anduin2017/HowToCook)集成
1. 目前采用力大砖飞的手解markdown版本，如果菜谱作者不讲武德不按照原项目规范写作，最后的效果就会很炸裂
2. 没有加入数据同步机制，需要手动将Anduin2017/HowToCook仓库克隆：
```shell
git clone https://github.com/Anduin2017/HowToCook /path/to/data/Dish
```
增加了「随机菜谱」和「怎么做XXX」两个指令

HowToCook function Integration

---

main.go

鉴于许多用户会直接发help调出聊天接口的帮助，从而得到南辕北辙的信息，或许需要调整内置帮助的指令

update help command

---

plugin/chess/core.go

昨天电脑硬盘出了点问题，代码 push 完还没运行测试呢，留了几个 bug
功能正常，可以 merge

[BUG FIX] 国际象棋插件 bug 修复

---

plugin/bilibili/bilibilipush.go
plugin/chess/core.go
plugin/kfccrazythursday/kfccrazythursday.go
plugin/lolicon/lolicon.go

fix chess & kfc && optimize lolicon & bilibili

---

README.md
main.go
plugin/robbery/robbery.go

https://github.com/FloatTech/ZeroBot-Plugin/issues/2#issuecomment-1681474703
add robbery plugin
添加打劫插件，打劫群友的Atri币
- 打劫[对方Q号|@对方QQ]
1. 受害者钱包少于1000不能被打劫
2. 打劫成功率 40%
4. 打劫失败罚款1000（钱不够不罚钱）
5. 保险赔付0-80%
6. 打劫成功获得对方0-5%+500的财产（最高1W）
7. 每日可打劫或被打劫一次
8. 打劫失败不计入次数
感谢 @LHyphen review

add robbery plugin

---

plugin/guessmusic/guessmusic.go
plugin/guessmusic/main.go

1. 修复：正确答案变小写、简体的问题
原先是把标准答案转小写、简体，然后再和输入答案比较。现在是每次比较的时候，都对标准答案和输入答案进行转换。是否要再加个变量先把转换后的标准答案存起来，比较的时候用。
2. 抽选歌曲的时候，只抽选本地已经下载好的歌曲
原先抽歌的时候有概率会调用API,改成只从下载好的歌曲里选取
3. 将插件改为默认禁用
因为下载的API失效了，不过依然可以通过其他方式添加歌曲
4. 新功能：提供猜歌选项
如图

Update guessmusic plugin

---

plugin/gif/context.go
plugin/gif/logo.go
plugin/gif/run.go

[issues 900] Update gif plugin for image cache
修改gif插件图片保存方式
头像统一保存在`user/qqid.gif`
生成的图片保存在 `user/被@的人qqid/`

[issues 900] Update gif plugin for image cache

---

plugin/dish/dish.go

`PrefixRule` 的 `ctx.State` 具有 `"args"` 键，而 `FullMatchRule` 并不具有，https://github.com/FloatTech/ZeroBot-Plugin/commit/879948a5c4723d4986608ec362195e8ed48a9cd0 之后，`ctx.NickName()` 调用 `ctx.State["args"]` 时访问了不存在的键，引发 `panic`。
鉴于 `name` 变量仅用于输出用户的昵称，无需从 `args`/`at` 获取昵称，因此使用能够满足需求的 `ctx.CardOrNickName(ctx.Event.UserID)` 来获取用户群昵称或昵称。

修复 FullMatchRule 中调用 ctx.NickName() 的 panic 问题

---

plugin/dish/dish.go

`db.Find` 所用的 `condition` 中，关键词没有被一对 `'`包裹，调用时会报错 `SQL logic error: near "%": syntax error (1)`。
返回结果时，应当返回找到的菜谱名 `d.Name`，而不是用户输入的关键词 `dishName`。
如用户输入的关键词未搜索到结果，给予提示。

[dish] fix: 关键词搜寻功能

---

plugin/robbery/robbery.go

fix robbery bug：Wallet is negative。
修复了打劫失败可能导致钱包为负数的情况。
先把插件给修了
API的修改好像有争议，加上技术菜，改的比较费力,就先搁置了

fix robbery bug：Wallet is negative

---

plugin/robbery/robbery.go

update robbery, fix：spelling mistakes

---

README.md
plugin/mcfish/pole.go

1. 去除README文件中gocqhttp相关内容
2. 修正mcfish中鱼竿名写死的问题

README remove gocqzbp & mcfish Modify Text

---

plugin/mcfish/pole.go

合成鱼竿未考虑鱼竿articles.Number>1的情况。
如果要修复这个问题，需要重构这块代码
所以梭哈功能直接按照原有思路，生成多个Number=1的鱼竿。

[mcfish] 修复鱼竿Number大于1，合成时少鱼竿的情况

---

plugin/mcfish/fish.go
plugin/mcfish/main.go
plugin/mcfish/pole.go
plugin/mcfish/store.go

- 不使用梭哈功能合成鱼竿时，生成鱼竿仍然按梭哈合成计算，导致鱼竿可能多给
- 完善提示文本
问题描述： upgradeNum 参数在一开始就按照梭哈的方式进行赋值。导致使用普通合成，生成新鱼竿时鱼竿数量是按照梭哈给的（鱼竿多给了）
解决方法：改成用list[]来计算用户合成鱼竿的数量。

fix(mcfish): 合成的鱼竿可能多给

---

README.md
main.go
plugin/mcfish/fish.go
plugin/qqwife/favorSystem.go
plugin/robbery/robbery.go
plugin/score/draw.go
plugin/wallet/wallet.go

[Feat] Supports configure custom coin name

---

go.mod
go.sum
plugin/aireply/ai_tts.go
plugin/aireply/main.go

fix: aireply: 修复文字回复模式

---

plugin/dish/dish.go

fix(fish): 修复客官名显示为菜名的问题

---

plugin/wordle/wordle.go

猜单词插件执行到最后一行会产生错误无法正确输出，原因是img数据为空，这里调整了代码位置来修复这个错误。

fix:修复猜单词插件最后一轮无法正常发送的错误

---

plugin/bilibili/card2msg.go

去掉获取up主粉丝数的部分 接口请求失败会导致整个b站链接解析失败

处理b站解析获取卡片失败的问题

---

plugin/niuniu/main.go

如题，在出售牛子的时候删除缓存，并且修改了赎牛牛的错误处理逻辑，添加了部分注释。

fix: 修复 niuniu 插件 bug，修改标点，添加部分注释
